CREATE EXTENSION IF NOT EXISTS postgis;

CREATE TABLE system_user (
    id UUID PRIMARY KEY,
    username VARCHAR(255) NOT NULL UNIQUE,
    password_hash VARCHAR(255) NOT NULL,
    role VARCHAR(50) NOT NULL,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    created_by UUID,
    created_at TIMESTAMP,
    updated_by UUID,
    updated_at TIMESTAMP,
    deleted BOOLEAN DEFAULT FALSE
);

CREATE TABLE refresh_token (
    id UUID PRIMARY KEY,
    token VARCHAR(255) NOT NULL UNIQUE,
    expiry_date TIMESTAMP WITH TIME ZONE NOT NULL,
    user_id UUID NOT NULL REFERENCES system_user(id) ON DELETE CASCADE
);

CREATE TABLE job_site (
    id UUID PRIMARY KEY,
    project_code VARCHAR(255) NOT NULL UNIQUE,
    site_name VARCHAR(255) NOT NULL,
    latitude DECIMAL(9,6) NOT NULL,
    longitude DECIMAL(9,6) NOT NULL,
    geofence_radius_meters INTEGER NOT NULL,
    accumulated_cost DECIMAL(12,2) NOT NULL DEFAULT 0.00,
    created_by UUID,
    created_at TIMESTAMP,
    updated_by UUID,
    updated_at TIMESTAMP,
    deleted BOOLEAN DEFAULT FALSE
);

CREATE TABLE equipment (
    id UUID PRIMARY KEY,
    asset_tag VARCHAR(255) NOT NULL UNIQUE,
    status VARCHAR(50) NOT NULL,
    current_engine_hours DECIMAL(10,2),
    internal_hourly_rate DECIMAL(10,2) NOT NULL DEFAULT 0.00,
    insurance_expiration DATE NOT NULL,
    created_by UUID,
    created_at TIMESTAMP,
    updated_by UUID,
    updated_at TIMESTAMP,
    deleted BOOLEAN DEFAULT FALSE
);

CREATE TABLE operator (
    id UUID PRIMARY KEY,
    first_name VARCHAR(255) NOT NULL,
    last_name VARCHAR(255) NOT NULL,
    license_expiration DATE NOT NULL,
    created_by UUID,
    created_at TIMESTAMP,
    updated_by UUID,
    updated_at TIMESTAMP,
    deleted BOOLEAN DEFAULT FALSE
);

CREATE TABLE dispatch_allocation (
    id UUID PRIMARY KEY,
    equipment_id UUID NOT NULL REFERENCES equipment(id),
    operator_id UUID NOT NULL REFERENCES operator(id),
    job_site_id UUID NOT NULL REFERENCES job_site(id),
    start_date TIMESTAMP NOT NULL,
    requires_heavy_transport BOOLEAN NOT NULL,
    status VARCHAR(50) NOT NULL,
    created_by UUID,
    created_at TIMESTAMP,
    updated_by UUID,
    updated_at TIMESTAMP,
    deleted BOOLEAN DEFAULT FALSE
);

CREATE TABLE maintenance_log (
    id UUID PRIMARY KEY,
    equipment_id UUID NOT NULL REFERENCES equipment(id),
    service_date TIMESTAMP NOT NULL,
    hours_at_service DECIMAL(10,2) NOT NULL,
    service_type VARCHAR(50) NOT NULL,
    total_cost DECIMAL(12,2) NOT NULL,
    notes TEXT,
    created_by UUID,
    created_at TIMESTAMP,
    updated_by UUID,
    updated_at TIMESTAMP,
    deleted BOOLEAN DEFAULT FALSE
);

-- Hibernate Envers Audit Tables
CREATE TABLE revinfo (
    rev INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    revtstmp BIGINT
);

CREATE TABLE equipment_aud (
    id UUID NOT NULL,
    rev INTEGER NOT NULL REFERENCES revinfo(rev),
    revtype SMALLINT,
    asset_tag VARCHAR(255),
    status VARCHAR(50),
    current_engine_hours DECIMAL(10,2),
    internal_hourly_rate DECIMAL(10,2),
    insurance_expiration DATE,
    deleted BOOLEAN,
    PRIMARY KEY (id, rev)
);

CREATE TABLE job_site_aud (
    id UUID NOT NULL,
    rev INTEGER NOT NULL REFERENCES revinfo(rev),
    revtype SMALLINT,
    project_code VARCHAR(255),
    site_name VARCHAR(255),
    latitude DECIMAL(9,6),
    longitude DECIMAL(9,6),
    geofence_radius_meters INTEGER,
    accumulated_cost DECIMAL(12,2),
    deleted BOOLEAN,
    PRIMARY KEY (id, rev)
);

CREATE TABLE dispatch_allocation_aud (
    id UUID NOT NULL,
    rev INTEGER NOT NULL REFERENCES revinfo(rev),
    revtype SMALLINT,
    equipment_id UUID,
    operator_id UUID,
    job_site_id UUID,
    start_date TIMESTAMP,
    requires_heavy_transport BOOLEAN,
    status VARCHAR(50),
    deleted BOOLEAN,
    PRIMARY KEY (id, rev)
);

CREATE TABLE maintenance_log_aud (
    id UUID NOT NULL,
    rev INTEGER NOT NULL REFERENCES revinfo(rev),
    revtype SMALLINT,
    equipment_id UUID,
    service_date TIMESTAMP,
    hours_at_service DECIMAL(10,2),
    service_type VARCHAR(50),
    total_cost DECIMAL(12,2),
    notes TEXT,
    deleted BOOLEAN,
    PRIMARY KEY (id, rev)
);

-- Enterprise Indexing
CREATE INDEX idx_job_site_geography ON job_site USING GIST (
    CAST(ST_SetSRID(ST_MakePoint(longitude, latitude), 4326) AS geography)
);
CREATE INDEX idx_dispatch_status ON dispatch_allocation(status);
CREATE INDEX idx_dispatch_equipment ON dispatch_allocation(equipment_id);
CREATE INDEX idx_equipment_status ON equipment(status);
CREATE INDEX idx_operator_license ON operator(license_expiration);
CREATE INDEX idx_user_username ON system_user(username);