import { Component, ChangeDetectionStrategy, inject, signal, computed, OnInit } from '@angular/core';
import { CommonModule } from '@angular/common';
import { JobSiteService } from '../../../../core/services/job-site.service';
import { JobSiteResponse } from '../../../../core/models/job-site';
import { JobSiteDrawer } from '../job-site-drawer/job-site-drawer';

@Component({
  selector: 'app-job-site-list',
  standalone: true,
  imports: [CommonModule, JobSiteDrawer],
  templateUrl: './job-site-list.html',
  changeDetection: ChangeDetectionStrategy.OnPush,
  styles: [`
    :host {
      display: block;
      width: 100%;
      height: 100%;
    }
    
    @keyframes slideFadeIn {
      0% {
        opacity: 0;
        transform: translateY(15px);
      }
      100% {
        opacity: 1;
        transform: translateY(0);
      }
    }
    
    .animate-row {
      animation: slideFadeIn 0.5s cubic-bezier(0.16, 1, 0.3, 1) forwards;
      opacity: 0; /* Starts hidden, animation reveals it */
    }
  `]
})
export class JobSiteList implements OnInit {
  private readonly jobSiteService = inject(JobSiteService);

  readonly jobSites = signal<JobSiteResponse[]>([]);
  readonly isLoading = signal<boolean>(true);
  readonly isDrawerOpen = signal<boolean>(false);
  readonly selectedJobSite = signal<JobSiteResponse | null>(null);
  readonly toastMessage = signal<{ detail: string; status: number } | null>(null);

  readonly searchQuery = signal<string>('');
  
  readonly filteredJobSites = computed(() => {
    const query = this.searchQuery().toLowerCase().trim();
    if (!query) return this.jobSites();
    return this.jobSites().filter(site => 
      site.projectCode.toLowerCase().includes(query) ||
      site.siteName.toLowerCase().includes(query)
    );
  });

  ngOnInit(): void {
    this.loadJobSites();
  }

  updateSearch(event: Event): void {
    this.searchQuery.set((event.target as HTMLInputElement).value);
  }

  loadJobSites(): void {
    this.isLoading.set(true);
    this.jobSiteService.getAll().subscribe({
      next: (data) => {
        this.jobSites.set(data);
        this.isLoading.set(false);
      },
      error: () => this.isLoading.set(false)
    });
  }

  openDrawer(jobSite?: JobSiteResponse): void {
    this.selectedJobSite.set(jobSite || null);
    this.isDrawerOpen.set(true);
  }

  closeDrawer(): void {
    this.isDrawerOpen.set(false);
    this.selectedJobSite.set(null);
  }

  onDrawerSuccess(): void {
    this.closeDrawer();
    this.loadJobSites();
  }

  exportLedger(site: JobSiteResponse): void {
    const docContent = `
=================================================
TITAN CORE LOGISTICS - PROJECT LEDGER INVOICE
=================================================
Project Code : ${site.projectCode}
Site Name    : ${site.siteName}
Coordinates  : ${site.latitude}, ${site.longitude}

-------------------------------------------------
FINANCIAL BREAKDOWN BUNDLE:
 - Machinery Depreciation & Usage
 - Operator Labor Wages
 - Consumed Diesel / Fuel Overrides
 - Heavy Transport (Lowboy Mob/Demob) Routing Fees

TOTAL ACCUMULATED PROJECT COST : $${site.accumulatedCost.toFixed(2)}
-------------------------------------------------

Generated by Titan System: ${new Date().toISOString()}
    `;
    // ... keep the rest of the export code identical
    const blob = new Blob([docContent], { type: 'text/plain' });
    const url = window.URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `Invoice_${site.projectCode}.txt`;
    a.click();
    window.URL.revokeObjectURL(url);
    
    this.toastMessage.set({ detail: `Financial ledger for ${site.projectCode} exported.`, status: 200 });
    setTimeout(() => this.toastMessage.set(null), 4000);
  }

  dismissToast(): void {
    this.toastMessage.set(null);
  }
}