version: '3.8'

services:
  db:
    image: postgis/postgis:15-3.3
    container_name: titan_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: titan_dispatch
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: titan_redis
    ports:
      - "6379:6379"
    volumes:
      - redisdata:/data

  api:
    build: .
    container_name: titan_api
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started
    ports:
      - "8080:8080"
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - REDIS_HOST=redis
      - DB_USER=postgres
      - DB_PASS=postgres

volumes:
  pgdata:
  redisdata: